name: Deploy React App to Hostinger

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/hostinger_deploy_key
          chmod 600 ~/.ssh/hostinger_deploy_key
          ssh-keyscan -p 65002 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure Deployment Folder Exists on Hostinger
        run: |
          ssh -i ~/.ssh/hostinger_deploy_key -o StrictHostKeyChecking=no -p 65002 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /home/u123262960/public_html/Tripsheetweb"

      - name: Upload React Build Files to Hostinger
        run: |
          rsync -avz --exclude=node_modules --exclude=dist --exclude=.git --exclude=.github \
          -e "ssh -i ~/.ssh/hostinger_deploy_key -o StrictHostKeyChecking=no -p 65002" \
          build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/u123262960/public_html/Tripsheetweb
